[package]
name = "tree-sitter-rake"
description = "Tree-sitter grammar for Rake, a vector-first SIMD language"
version = "0.5.0-beta"
authors = ["Kieran Rosenberg"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "rake"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/rakelang/tree-sitter-rake"
edition = "2021"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.26.11"
